# Generated by Django 4.2.5 on 2023-10-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theGames', '0002_studio_alter_game_release_date_alter_game_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(help_text='The company that created the platform. e.g., Sony, Microsoft, Nintendo.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='theGames.studio'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='games', to='theGames.platform'),
        ),
    ]
