# Generated by Django 4.2.5 on 2023-10-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGames', '0003_platform_alter_game_studio_game_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', to='theGames.platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
